# This file has been generated by node2nix 1.7.0. Do not edit!

{nodeEnv, fetchurl, fetchgit, globalBuildInputs ? []}:

let
  sources = {};
in
{
  pnpm = nodeEnv.buildNodePackage {
    name = "pnpm";
    packageName = "pnpm";
    version = "4.12.5";
    src = fetchurl {
      url = "https://registry.npmjs.org/pnpm/-/pnpm-4.12.5.tgz";
      sha512 = "EoAJjnlalTyXqG+ge0DMTlL+ZehA06+ns9F2zgEo/jrlW3WSU5LmUq5sEDODWRqJFikzVRBW6MW2FmfUOUmZWg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Fast, disk space efficient package manager";
      homepage = https://pnpm.js.org/;
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}