directory: ~/media/music/pebbles
library: ~/.local/share/beets/pebbles

import:
  copy: yes
  languages: en # In order of preference

plugins:
  - musicbrainz
  # - mbpseudo
  # - lyrics
  - fish
  - fetchart
  - lastgenre
  - convert
  - embedart
  - VGMplug

# mbpseudo:
#   scripts:
#     - Latn

convert:
  auto: yes
  copy_album_art: yes
  never_convert_lossy_files: yes
  format: opus
  formats:
    opus: ffmpeg -i $source -y -vn -acodec libopus -ab 128k $dest

fetchart:
  auto: yes
  cover_format: JPEG
  max_filesize: 4194304 # 4MiB

embedart:
  auto: no
