let mapleader = " " " <leader> = <space>

set packpath^=~/.local/share/vim " This is where the plugins I add with Nix will go

filetype plugin on
syntax enable

set history=1000 " How many commands neovim should remember

set ignorecase " Ignore case when searching...
set smartcase " ...but not when there's uppercase characters

set foldmethod=marker " The best way to fold :3

set number " Line numbers
set relativenumber " Relative line numbers
set nuw=1 " Do not make the number column thicker than it needs to be

set nojoinspaces " No double spaces when joining lines
set list " Explicitly display characters like \t
set listchars=tab:>\ ,trail:-,nbsp:+ " What characters to display explicitly

" tcqj is the default
" - "t" automatically wraps text
" - "c" automatically wraps comments
" - "q" allows re-flowing comments with gq
" - "j" removes comment leaders when joining lines
" - "r" automatically continues comments on enter
set formatoptions=tcqjr

set breakindent " Indentation-aware word wrapping.
set noexpandtab " Use tabs by default. Configured on a per-filetype basis
set shiftwidth=2 " Size of an indent
set tabstop=2 " Size of tab character
set shiftround " When using < or >, rounds to closest multiple of shiftwidth
set smartindent " Insert indents automatically

set splitbelow " Put new windows below current
set splitright " Put new windows right of current

set scrolloff=4 " Starts scrolling 4 lines from the edge of the screen

set termguicolors " True color support
set term=xterm-256color " Probably bad, but the above doesn't work otherwise

set lazyredraw " Don't redraw while executing macros
set autoread " Detect changes from the outside
au FocusGained,BufEnter * silent! checktime

set noruler " Do not show the cursor position in the bottom-right
set wildmenu " Autocomplete menu
set undofile " Preserve undo history
set undodir=~/.cache/vim/undo
set directory=~/.cache/vim/swap

" Let backspace delete over more stuff
set backspace=eol,start,indent

set incsearch " Incremental search
set hlsearch " Highlight search results
nnoremap <leader>s/ :noh<cr> " Hide search results

set nowrap
nnoremap <leader>sw :set wrap!<cr>

" Exit help menus
au FileType help,qf silent! nnoremap <buffer> qq :close<cr>

" Replace word in file
nnoremap <leader>rw :%s/<C-r><C-w>/

" Open file in project's directory
nnoremap <C-p> :find! ./**/

" Toggle the color column via <leader>sc
let default_colorcolumn=join(range(81,999),",")
nnoremap <leader>sc :execute
	\ "set colorcolumn=" . (&colorcolumn == "" ? default_colorcolumn : "")<CR>

" Since vim-classic does not have the -indentonly option of :retab!, we have
" to reproduce it manually.
function! RetabIndentonly()
	let l:state = winsaveview()
	execute "%!unexpand --first-only --tabs=".&tabstop
	call winrestview(l:state)
endfunction
nnoremap <leader>lt :call RetabIndentonly()<cr>

" Free up q & Q
nnoremap <C-q> q
nnoremap <C-S-q> Q
nnoremap q <nop>
nnoremap Q <nop>

" Save with Q
nnoremap Q :wqa<cr>

" Merge lines with qj
nnoremap qj J

" Different chords get remapped to f-keys by my Kanata config.
" Exit insert mode using *jk*
inoremap <f10> <esc>
vnoremap <f10> <esc>

" Use global clipboard using *cp*
nnoremap <f11> "+
vnoremap <f11> "+

" Save using *ji*
nnoremap <silent> <f12> :silent! write<cr>

" Set cursor shapes based on the mode we're in.
"
" I can't believe I'm saying this, but I found this fix in a YouTube video of
" all places! (https://www.youtube.com/watch?v=FcQjTXLrVUU)
let &t_SI = "\e[6 q"
let &t_EI = "\e[2 q"
let &t_SR = "\e[4 q"
set noshowmode " The cursor shape is enough for me

" These should make undercurl work
let &t_Cs = "\e[4:3m"
let &t_Ce = "\e[4:0m"

" Scuffed spell file auto-regeneration.
"
" I say scuffed because this sort of conflicts with Neovim's spellfiles (I
" have no idea whether the two use the same format for the binary version).
let s:spell_prefix="~/projects/personal/satellite/home/features/neovim/config/spell"
let s:spell_file=s:spell_prefix . "/en.utf-8.add.spl"
let s:add_file=s:spell_prefix . "/en.utf-8.add"

execute "set" "spellfile=".s:add_file
function! s:regen_spellfile()
	execute "silent!" "mkspell!" s:spell_file s:add_file
endfunction

call s:regen_spellfile()
au FocusGained * call s:regen_spellfile()

set spell
nnoremap <leader>ss :set spell!<cr>

" I don't think this would be needed if using a version of Vim that has the
" gitignore filetype!
au BufEnter .gitignore setlocal nospell

" Quickfix
function! ToggleQuickFix()
	if empty(filter(getwininfo(), 'v:val.quickfix'))
		copen
	else
		cclose
	endif
endfunction
nnoremap <silent> <leader>q :call ToggleQuickFix()<cr>

" Netrw
let g:netrw_list_hide="^\./$"

function! HidePat(pat)
	let g:netrw_list_hide.=",^".a:pat."$"
	execute "set wildignore+=**/".a:pat
endfunction

function! HideDir(dir)
	let g:netrw_list_hide.=",^".a:dir."$"
	execute "set wildignore+=**/".a:dir."**"
endfunction

call HideDir("build/")
call HideDir("dist/")
call HideDir("target/")
call HideDir("zig-pkg/")
call HideDir("zig-out/")
call HideDir(".zig-cache/")
call HideDir(".xwin-cache/")
call HideDir(".direnv/")
call HideDir(".git/")
call HidePat("result@")
call HidePat("*.swp")
call HidePat("*.spl")

set wildignore+=**/*.png
set wildignore+=**/*.jpg
set wildignore+=**/*.ico
set wildignore+=**/*.webp
set wildignore+=**/*.gif
set wildignore+=**/*.pdf
set wildignore+=**/secrets*.yaml
set wildignore+=**/flake.lock

let g:netrw_banner=0
let g:netrw_altfile=1 " Keep netrw out of the alt file
" This is better than :Explore, since :Explore removes the overridden file
" from being the altfile, which is super problematic.
nnoremap <leader>f :execute "edit" expand("%:h")<cr>

" Finally, my custom theme :3
colorscheme meow

" Note that this will run into race conditions if run in multiple instances of
" Vim at once, but that's ok :3
"
" A "better" implementation would generate some unique filename at the start.
" Unfortunately, they call me a Haskell expression, for I am very lazy.
function! YaziEdit()
	execute "silent" "!yazi"
		\ "--chooser-file /tmp/vim-yazi-chosen"
		\ expand("%:h")

	if filereadable("/tmp/vim-yazi-chosen")
		let l:path=readfile("/tmp/vim-yazi-chosen")[0]
		" We don't want these to influence future runs
		silent !rm /tmp/vim-yazi-chosen
		execute "edit!" l:path
	endif
	redraw!
endfunction

nnoremap <C-S-f> :call YaziEdit()<cr>
