{ config, ... }:
{
  # {{{ Set up my custom impermanence wrapper
  satellite.persistence = {
    # Actual data/media (eg: projects, images, videos, etc)
    at.data.bounds.source = "/persist/data${config.home.homeDirectory}";

    # App state I want to keep
    at.state.bounds.source = "/persist/state${config.home.homeDirectory}";

    # App state which I should be able to delete on a whim
    at.cache.bounds.source = "/persist/local/cache${config.home.homeDirectory}";
  };
  # }}}
  # {{{ XDG dirs
  # The lack of "~/Desktop" and "~/Downloads" is intentional!
  satellite.persistence.at.data.directories = [
    config.xdg.userDirs.documents
    config.xdg.userDirs.pictures
    config.xdg.userDirs.music
    config.xdg.userDirs.videos
    config.xdg.userDirs.extraConfig.PROJECTS
  ];
  # }}}
  # {{{ OpenTabletDriver
  satellite.persistence.at.state.at.open-tablet-driver.directories = [
    "${config.xdg.configHome}/OpenTabletDriver"
  ];
  # }}}
  # {{{ Programming tooling
  # {{{ Elm
  satellite.persistence.at.cache.at.elm.directories = [ ".elm" ];
  # }}}
  # {{{ Fly.io
  satellite.persistence.at.state.at.fly-io.directories = [ ".fly" ];
  # }}}
  # {{{ Haskell
  satellite.persistence.at.cache.at.haskell.directories = [
    ".ghc"
    ".stack"
    ".local/state/cabal"
    "${config.xdg.cacheHome}/stack"
    "${config.xdg.cacheHome}/ghcide"
    "${config.xdg.cacheHome}/cabal"
  ];

  # TODO: should I move this in its own Haskell-specific file?
  home.file.".stack/config.yaml".text = builtins.toJSON { notify-if-nix-on-path = false; };
  # }}}
  # {{{ Nodejs
  satellite.persistence.at.cache.at.nodejs = {
    files = [
      # ".yarnrc" # auto-generated by yarn
      ".node_repl_history"
      # ".ts_node_repl_history"
    ];

    directories = [
      # Node & npm
      "${config.xdg.cacheHome}/node-gyp"
      ".npm"

      # Yarn
      "${config.xdg.cacheHome}/yarn"

      # Pnpm
      "${config.xdg.cacheHome}/pnpm"
      "${config.xdg.dataHome}/pnpm"
      ".local/state/pnpm"
    ];
  };
  # }}}
  # {{{ Purescript
  satellite.persistence.at.cache.at.purescript.directories = [
    "${config.xdg.dataHome}/purescript"
    "${config.xdg.cacheHome}/spago"
  ];
  # }}}
  # {{{ Python
  satellite.persistence.at.cache.at.python = {
    files = [ ".python_history" ];

    directories = [
      ".ipython"
      ".jupyter"
      "${config.xdg.dataHome}/jupyter"
      "${config.xdg.cacheHome}/pip"
    ];
  };
  # }}}
  # {{{ Rust
  satellite.persistence.at.cache.at.rust.directories = [
    ".cargo"
    ".rustup"
  ];
  # }}}
  # }}}
  # {{{ Desktop apps
  # {{{ QBittorrent
  satellite.persistence.at.state.at.qbittorrent.directories = [
    "${config.xdg.configHome}/qBittorrent" # Config options
  ];

  satellite.persistence.at.cache.at.qbittorrent.directories = [
    "${config.xdg.dataHome}/qBittorrent" # Torrent files, logs, etc
  ];
  # }}}
  # {{{ Signal
  satellite.persistence.at.state.at.signal.directories = [
    "${config.xdg.configHome}/Signal" # Why tf does signal store it's state here 💀
  ];
  # }}}
  # {{{ Freetube
  satellite.persistence.at.state.at.freetube.directories = [
    "${config.xdg.configHome}/FreeTube" # Why tf does freetube store it's state here 💀
  ];
  # }}}
  # {{{ Whatsapp
  satellite.persistence.at.state.at.whatsapp.directories = [
    "${config.xdg.configHome}/whatsapp-for-linux"
    # TODO(2025-12-10): Am I sure this is supposed to be this instead of `dataHome`?
    "${config.xdg.stateHome}/whatsapp-for-linux"
  ];

  satellite.persistence.at.cache.at.whatsapp.directories = [
    "${config.xdg.cacheHome}/whatsapp-for-linux"
  ];
  # }}}
  # {{{ Element
  satellite.persistence.at.state.at.element.directories = [
    "${config.xdg.configHome}/Element"
  ];
  # }}}
  # {{{ Fluffychat
  satellite.persistence.at.state.at.fluffy.directories = [
    "${config.xdg.dataHome}/chat.fluffy.fluffychat"
  ];
  # }}}
  # {{{ Bitwarden
  satellite.persistence.at.state.at.bitwarden.directories = [
    "${config.xdg.configHome}/Bitwarden"
  ];
  # }}}
  # {{{ Gnome keyring
  services.gnome-keyring.enable = true; # TODO: move this to a proper location
  satellite.persistence.at.state.at.gnome-keyring.directories = [
    "${config.xdg.dataHome}/keyrings"
  ];
  # }}}
  # {{{ Gnome calendar
  satellite.persistence.at.state.at.gnome-calendar.directories = [
    "${config.xdg.configHome}/evolution"
    "${config.xdg.dataHome}/evolution"
  ];
  # }}}
  # {{{ Libreoffice
  satellite.persistence.at.cache.at.libreoffice.directories = [
    "${config.xdg.configHome}/libreoffice"
  ];
  # }}}
  # {{{ Obsidian
  satellite.persistence.at.state.at.obsidian.directories = [
    "${config.xdg.configHome}/obsidian"
  ];
  # }}}
  # {{{ Anki
  satellite.persistence.at.state.at.anki.directories = [
    "${config.xdg.dataHome}/Anki2"
  ];
  # }}}
  # {{{ Aseprite
  satellite.persistence.at.state.at.aseprite.directories = [
    "${config.xdg.configHome}/aseprite"
  ];
  # }}}
  # }}}
  # {{{ Cli
  # {{{ Sops
  satellite.persistence.at.state.at.sops.directories = [
    "${config.xdg.configHome}/sops/age"
  ];
  # }}}
  # {{{ QMK
  home.sessionVariables.QMK_HOME = "${config.xdg.dataHome}/qmk";
  satellite.persistence.at.state.at.qmk.directories = [
    config.home.sessionVariables.QMK_HOME
    "${config.xdg.dataHome}/qmk-sonix"
  ];
  # }}}
  # }}}
}
