# {{{ General
<C-backtab> = :prev-tab<Enter>
<C-tab>     = :next-tab<Enter>

<C-z> = :suspend<Enter>
<C-t> = :term<Enter>
? = :help keys<Enter>
# }}}
# {{{ Messages
[messages]
q      = :quit<Enter>

g = :select 0<Enter>
G = :select -1<Enter>
j = :next<Enter>
k = :prev<Enter>

<C-d>  = :next 50%<Enter>
<C-u>  = :prev 50%<Enter>
<PgDn> = :next 100%<Enter>
<PgUp> = :prev 100%<Enter>

J = :next-folder<Enter>
K = :prev-folder<Enter>
H = :collapse-folder<Enter>
L = :expand-folder<Enter>

v       = :mark -t<Enter>
<Space> = :mark -t<Enter>:next<Enter>
V       = :mark -v<Enter>

t     = :toggle-threads<Enter>
zc    = :fold<Enter>
zo    = :unfold<Enter>
za    = :fold -t<Enter>
zM    = :fold -a<Enter>
zR    = :unfold -a<Enter>
<tab> = :fold -t<Enter>

zz = :align center<Enter>
zt = :align top<Enter>
zb = :align bottom<Enter>

<Enter> = :view<Enter>
d = :choose -o y 'Really delete this message' delete-message<Enter>
D = :delete<Enter>
a = :archive flat<Enter>
A = :unmark -a<Enter>:mark -T<Enter>:archive flat<Enter> # archive thread
T = :mv Trash<Enter>

m = :compose<Enter>
b = :bounce<space>

rr = :reply -a<Enter>
rq = :reply -aq<Enter>
Rr = :reply<Enter>
Rq = :reply -q<Enter>

$ = :term<space>
| = :pipe<space>

/ = :search<space>
\ = :filter<space>
n = :next-result<Enter>
N = :prev-result<Enter>
<Esc> = :clear<Enter>

s = :split<Enter>
S = :vsplit<Enter>

pl = :patch list<Enter>
pa = :patch apply <Tab>
pd = :patch drop <Tab>
pb = :patch rebase<Enter>
pt = :patch term<Enter>
ps = :patch switch <Tab>

[messages:folder=Drafts]
<Enter> = :recall<Enter>
# }}}
# {{{ View
[view]
/ = :toggle-key-passthrough<Enter>/
q = :close<Enter>
o = :open<Enter>
S = :save<space>
| = :pipe<space>
D = :delete<Enter>
A = :archive flat<Enter>
T = :mv Trash<Enter>:close<Enter>

<C-y> = :copy-link <space>
<C-l> = :open-link <space>

f = :forward<Enter>
rr = :reply -a<Enter>
rq = :reply -aq<Enter>
Rr = :reply<Enter>
Rq = :reply -q<Enter>

H = :toggle-headers<Enter>
J = :next<Enter>
K = :prev<Enter>
<C-k> = :prev-part<Enter>
<C-j> = :next-part<Enter>

[view::passthrough]
$noinherit = true
$ex        = <C-:>
<Esc>      = :toggle-key-passthrough<Enter>
# }}}
# {{{ Compose
[compose]
$noinherit = true
$ex        = <C-:>
$complete  = <C-o>

<C-k> = :prev-field<Enter>
<C-j> = :next-field<Enter>
<C-h> = :switch-account -p<Enter>
<C-l> = :switch-account -n<Enter>

<tab>       = :next-field<Enter>
<backtab>   = :prev-field<Enter>
<C-backtab> = :prev-tab<Enter>
<C-tab>     = :next-tab<Enter>

# Keybindings used when the embedded terminal is selected in the compose view
[compose::editor]
$noinherit = true
$ex        = <C-:>

<C-k>       = :prev-field<Enter>
<C-j>       = :next-field<Enter>
<C-backtab> = :prev-tab<Enter>
<C-tab>     = :next-tab<Enter>

# Keybindings used when reviewing a message to be sent
# Inline comments are used as descriptions on the review screen
[compose::review]
y = :send<Enter> # Send
n = :abort<Enter> # Abort (discard message, no confirmation)
s = :sign<Enter> # Toggle signing
x = :encrypt<Enter> # Toggle encryption to all recipients
v = :preview<Enter> # Preview message
p = :postpone<Enter> # Postpone
e = :edit<Enter> # Edit (body)
E = :edit -e<Enter> # Edit (body and headers)
a = :attach<space> # Add attachment
d = :detach<space> # Remove attachment
# }}}
# {{{ Terminal
[terminal]
$noinherit = true
$ex = <C-:>
<C-backtab> = :prev-tab<Enter>
<C-tab>     = :next-tab<Enter>
# }}}
