[private]
default:
  @just --list

[doc("Prints the differences between the current and desired DNS records")]
[group("dns")]
dns-diff:
  nix run .#octodns-sync --show-trace -- --force

[doc("Syncs DNS records using octodns")]
[group("dns")]
dns-sync:
  nix run .#octodns-sync -- --doit --force
