[private]
default:
  @just --list

[doc("Prints the differences between the current and desired DNS records")]
[group("dns")]
dns-diff:
  nix run .#octodns-sync --show-trace -- --force

[doc("Syncs DNS records using octodns")]
[group("dns")]
dns-sync:
  nix run .#octodns-sync -- --doit --force

[doc("Clears every DNS record")]
[group("dns")]
dns-clear zoneid bearer:
  #!/usr/bin/env bash
  set -euo pipefail # Fail on errors and whatnot

  # Taken from https://developers.cloudflare.com/dns/zone-setups/troubleshooting/delete-all-records/
  curl --silent "https://api.cloudflare.com/client/v4/zones/{{zoneid}}/dns_records?per_page=50000" \
  --header "Authorization: Bearer {{bearer}}" \
  | jq --raw-output '.result[].id' | while read id
  do
    echo "🧹 Deleting '$id' record in zone '{{zoneid}}'"
    curl --silent --request DELETE "https://api.cloudflare.com/client/v4/zones/{{zoneid}}/dns_records/$id" \
  --header "Authorization: Bearer {{bearer}}"
  done

  echo "🚀 All done!"
